export const images = {
  hero: '/images/nw-detail-studio-hero.jpg',
  darkStudio: '/images/nw-detail-studio-dark-studio.jpg',
  blackClean: '/images/nw-detail-studio-black-clean.jpg',
  ceramicCoatingReflection: '/images/nw-detail-ceramic-coating-reflrection.jpg',
  ceramicCoatingCloseUpApplication: '/images/nw-detail-ceramic-coating-close-up-application.jpg',
  ceramicCoatingApplicator: '/images/nw-detail-studio-ceramic-coating-applicator.jpg',
  ceramicCoatingWaterBeading: '/images/nw-detail-studio-ceramic-coating-water-beading.jpg',
  waterBeading: '/images/nw-detail-studio-water-beading.jpg',
  dirtyInterior: '/images/nw-detail-studio-dirty-interior.jpg',
  interiorClean: '/images/nw-detail-studio-interior-clean.jpg',
  suvInteriorClean: '/images/nw-detail-studio-suv-interior-clean .jpg',
  paintBad: '/images/nw-detail-studio-paint-bad.jpg',
  paintGood: '/images/nw-detail-studio-paint-good.jpg',
  paintCloseUp: '/images/nw-detail-studio-paint-close-up.jpg',
  wheelDirty: '/images/nw-detail-studio-wheel-dirty.jpg',
  wheelBrakeDust: '/images/nw-detail-studio-wheel-brake-dust.jpg',
  wheelClean: '/images/nw-detail-studio-wheel-clean.jpg',
  wheelGlossy: '/images/nw-detail-studio-wheel-glossy.jpg',
  wheelBrush: '/images/nw-detail-studio-wheel-brush.jpg',
  wheelDetailBrush: '/images/nw-detail-studio-wheel-detail-brush.jpg',
  wheelDressing: '/images/nw-detail-studio-wheel-dressing.jpg',
  dashWiping: '/images/nw-detail-studio-dash-wiping.jpg',
  interiorVacuuming: '/images/nw-detail-studio-interior-vacuuming.jpg',
  interiorSteamCleaning: '/images/nw-detail-studio-interior-steam-cleaning.jpg',
  upholsteryExtraction: '/images/nw-detail-studio-upholstery-extraction.jpg',
  foam: '/images/nw-detail-studio-foam.jpg',
  washMitt: '/images/nw-detail-studio-wash-mitt.jpg',
  polishCloseup: '/images/nw-detail-studio-polish-closeup.jpg',
  polish: '/images/nw-detail-studio-polish.jpg',
  cleanBoat: '/images/nw-detail-studio-clean-boat.jpg',
  cleanRv: '/images/nw-detail-studio-clean-rv.jpg',
  cleanTruck: '/images/nw-detail-studio-clean-truck.jpg',
  suvClean: '/images/nw-detail-studio-suv-clean.jpg',
  inspectionLight: '/images/nw-detail-studio-inspection-light.jpg',
  underLights: '/images/nw-detail-studio-under-lights.jpg',
  detailerAtWork01: '/images/nw-detail-studio-detailer-at-work-01.jpg',
  detailerAtWork02: '/images/nw-detail-studio-detailer-at-work-02.jpg',
  detailerAtWork03: '/images/nw-detail-studio-detailer-at-work-03.jpg',
  detailerAtWork04: '/images/nw-detail-studio-detailer-at-work-04.jpg',
  detailerAtWork05: '/images/nw-detail-studio-detailer-at-work-05.jpg',
  drying: '/images/nw-detail-studio-drying.jpg',
  pressureWash: '/images/nw-detail-studio-pressure-wash.jpg',
  headlightCloseUp: '/images/nw-detail-studio-headlight-close-up.jpg',
} as const;

export type ImageKey = keyof typeof images;
